markdown: rdiscount
pygments: true

#multiviews: true
#only works with https://github.com/stammy/jekyll, explained below

source:      .
destination: ./_site
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:title.html

#base_url: http://paulstamatiou.com
base_url: /
description: "iOS development, startups."
root_desc: "HectorRamos.com"

rdiscount:
  extensions: []
  
exclude: ['Rakefile', 'README.markdown', 'config.rb']