markdown: rdiscount
pygments: true

multiviews: true
#only works with https://github.com/stammy/jekyll, explained below

source:      .
destination: ./_site
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:title.html

base_url: http://hectorramos.com
#base_url: http://jekyll.dev
#base_url: http://publicaccion.net
description: "iOS development, startups."
root_desc: "HectorRamos.com"

rdiscount:
  extensions: []
  
exclude: ['Rakefile', 'README.markdown', 'config.rb', 'redirect.txt', 'README.textile', 'TODO.txt', 'new.txt', 'old.txt', '_site.zip', '.htaccess']